### ISSUE TITLE
Error while running test_core.py

### ISSUE THREAD

**Issue by jtanios** [dmlc/keras#49]
test_core.py:433:                                                                                                  │
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
/usr/local/lib/python2.7/dist-packages/keras/utils/test_utils.py:80: in layer_test                                 │
    y = layer(x)                                                                                                   │  1  [                                          0.0%]     5  [                                          0.0%]
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:546: in __call__                                   │  2  [                                          0.0%]     6  [                                          0.0%]
    self.build(input_shapes[0])                                                                                    │  3  [||                                        1.3%]     7  [                                          0.0%]
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:1240: in build                                         │  4  [                                          0.0%]     8  [                                          0.0%]
    constraint=self.W_constraint)                                                                                  │  Mem[|||||                              347/15039MB]     Tasks: 51, 30 thr; 1 running
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:418: in add_weight                                 │  Swp[                                         0/0MB]     Load average: 0.09 0.05 0.05
    weight = initializer(shape, name=name)                                                                         │                                                          Uptime: 05:02:27
/usr/local/lib/python2.7/dist-packages/keras/initializations.py:66: in glorot_uniform                              │
    return uniform(shape, s, name=name)                                                                            │  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
/usr/local/lib/python2.7/dist-packages/keras/initializations.py:33: in uniform                                     │ 2733 ubuntu     20   0 24596  2248  1460 R  0.0  0.0  1:11.40 htop
    return K.random_uniform_variable(shape, -scale, scale, name=name)                                              │ 1297 ubuntu     20   0  107M  2052  1000 S  0.0  0.0  0:03.50 sshd: ubuntu@pts/0
/usr/local/lib/python2.7/dist-packages/keras/backend/mxnet_backend.py:18: in func_wrapper                          │ 2487 ubuntu     20   0  286M 46612  6964 S  0.0  0.3  0:06.04 /usr/bin/python3 /usr/local/bin/jupyter-notebook
    ret = func(*args, **kwargs)                                                                                    │ 1142 postgres   20   0  240M  1648   300 S  0.0  0.0  0:00.14 postgres: wal writer process
/usr/local/lib/python2.7/dist-packages/keras/backend/mxnet_backend.py:828: in random_uniform_variable              │ 1323 ubuntu     20   0 26528  3804  1208 S  0.0  0.0  0:12.40 tmux
    value = mx.random.uniform(low=low, high=high, dtype='float32', shape=shape)                                    │ 2548 ubuntu     20   0 22440  4940  1880 S  0.0  0.0  0:00.26 -bash
mxnet/cython/ndarray.pyx:167: in ndarray._make_ndarray_function.generic_ndarray_function (mxnet/cython/ndarray.cpp:│ 3118 ubuntu     20   0  572M 41256  5952 S  0.0  0.3  0:00.24 /usr/bin/python2.7 -m ipykernel -f /run/user/1000/
3614)                                                                                                              │ 1060 root       20   0 19320   860   528 S  0.0  0.0  0:01.15 /usr/sbin/irqbalance
    ???                                                                                                            │  994 root       20   0  336M  6732  5200 S  0.0  0.0  0:00.24 NetworkManager
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _│ 1144 postgres   20   0   99M  1756   356 S  0.0  0.0  0:00.22 postgres: stats collector process
                                                                                                                   │ 2509 ubuntu     20   0  573M 40408  6036 S  0.0  0.3  0:00.74 /usr/bin/python2.7 -m ipykernel -f /run/user/1000/
>   ???                                                                                                            │ 3105 ubuntu     20   0  572M 41256  5952 S  0.0  0.3  0:00.84 /usr/bin/python2.7 -m ipykernel -f /run/user/1000/
E   MXNetError: Invalid Parameter format for dtype expect int but value='float32', in operator uniform(name="", low│ 2494 ubuntu     20   0  573M 40408  6036 S  0.0  0.3  0:01.58 /usr/bin/python2.7 -m ipykernel -f /run/user/1000/
="-1.09544511501", shape="(3, 2)", dtype="float32", high="1.09544511501")

**Comment by duzhen1996** [comment]
Have you solved it? I get similar error like "Invalid Parameter format" when Keras works with MXNet. Thank you.
