### ISSUE TITLE
Error with Theano backend and multiple GPUs

### ISSUE THREAD

**Issue by beeva-juangomez** [dmlc/keras#78]
I'm trying to use Theano backend with multiple GPUs and I'm getting this error: ValueError: Invalid argument "context" passed to K.function. However, if i'm running TheanoGPU test script everything is correct. Any idea?

Thanks!

**Comment by sandeep-krishnamurthy** [comment]
Hello,
Multi-GPUs via context parameter is the new functionality added only for MXNet backend. Theano backend does not support this functionality.

**Comment by beeva-juangomez** [comment]
Thank you, closing the issue
