### ISSUE TITLE
keras_shape and backend_shape mismatch with shape changing operation

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [dmlc/keras#83]
Here is the detailed bug report from the user - https://github.com/bgshin/mxnet_cnn/blob/master/src/bug.md

# Summary of the issue:

* keras_shape and backend_shape doesn't match after applying shape changing operations.
When performing an tensor operation (like multiplication), keras tries to check the validity of a given operation using keras_shape.
* If the shape of a tensor is changed by some operation (eg. slicing a tensor), then both of the keras_shape and backend_shape should be changed.
* However, for mxNet, only backend_shape is changed.
This causes an error when applying an operations that requires correct shape information.

**Comment by lupesko** [comment]
+1

**Comment by sandeep-krishnamurthy** [comment]
Create PR for the fix - https://github.com/dmlc/keras/pull/84

**Comment by sandeep-krishnamurthy** [comment]
Please rebuild from latest master to get the fix.

$ git clone --recursive https://github.com/dmlc/keras
$ cd keras
$ python setup.py install --user

In the meantime, we will work on updating the pip package.
